apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mern-stack

resources:
  - namespace.yaml
  - mysql/secret.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml